{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hengai.module_aicaring",
    "module": "flutter_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-3f3e560236539b7e2702f5ac790b2a4691b32d49"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-3f3e560236539b7e2702f5ac790b2a4691b32d49"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-3f3e560236539b7e2702f5ac790b2a4691b32d49"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-3f3e560236539b7e2702f5ac790b2a4691b32d49"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.0.aar",
          "url": "flutter_release-1.0.aar",
          "size": 3963544,
          "sha512": "e5840ba1523e04171a54ef5bcb8e502b3e52f90011f8e3e4c7718dd3294d7fdeffeba814097069d2d80d4f59370ee024d4885ce33f8af05a04cd95c6017ca132",
          "sha256": "b6b4231bba25d5cab73c1d5cb0b8e36fcfcd2b241cebbfb87e630b9925056be2",
          "sha1": "7d7e5bd1ae9ab8d101b057d863be529ea0cf2d0f",
          "md5": "9f65b3ab5a3e304b4dd0035d4e864d7e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-3f3e560236539b7e2702f5ac790b2a4691b32d49"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-3f3e560236539b7e2702f5ac790b2a4691b32d49"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-3f3e560236539b7e2702f5ac790b2a4691b32d49"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-3f3e560236539b7e2702f5ac790b2a4691b32d49"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.0.aar",
          "url": "flutter_release-1.0.aar",
          "size": 3963544,
          "sha512": "e5840ba1523e04171a54ef5bcb8e502b3e52f90011f8e3e4c7718dd3294d7fdeffeba814097069d2d80d4f59370ee024d4885ce33f8af05a04cd95c6017ca132",
          "sha256": "b6b4231bba25d5cab73c1d5cb0b8e36fcfcd2b241cebbfb87e630b9925056be2",
          "sha1": "7d7e5bd1ae9ab8d101b057d863be529ea0cf2d0f",
          "md5": "9f65b3ab5a3e304b4dd0035d4e864d7e"
        }
      ]
    }
  ]
}
